apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsd
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 3
  strategy:
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
       —name: nodejs
          image: us-central1-docker.pkg.dev/gcp-kubernetes-project-402813/my-repository/nodejs
          ports:
           —containerPort: 3000
            protocol: TCP